language: php

php:
  - 5.5
  - 5.6

before_script:
  - composer selfupdate
  - composer install
  - phpenv rehash
  - wget https://scrutinizer-ci.com/ocular.phar

script: 
  - phpunit --coverage-text --coverage-clover coverage.xml